# Generated by Django 3.2.4 on 2021-08-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isComplete',
            field=models.BooleanField(default=False, verbose_name='Complete?'),
        ),
    ]
